
; main server binary
(executable
  (name         main)
  (public_name  ftw-server)
  (package      ftw-server)
  (preprocess
    (pps lwt_ppx dream-html.ppx)
  )
  (libraries
     ftw ftw_core ftw_api
     dream dream-html dream-htmx
     fmt fmt.cli logs logs.cli logs.fmt
     cmdliner containers jsont jsont.bytesrw
     dune-site
  )
)

; assets as files
(generate_sites_module
  (module sites)
  (sites ftw-server)
)

