
; main server binary
(executable
  (name         main)
  (public_name  ftw-server)
  (package      ftw-server)
  (preprocess
    (pps lwt_ppx ppx_deriving.show ppx_deriving_yojson)
  )
  (libraries
     ftw ftw_core ftw_api dream
     fmt fmt.cli logs logs.cli logs.fmt
     cmdliner containers yojson jsont jsont.bytesrw
     dune-site
  )
)

; assets as files
(generate_sites_module
  (module sites)
  (sites ftw-server)
)

