
[event]
  name = "Printemps 4 Temps"
  start_date = 2019-05-24
  end_date = 2019-05-26

[event.comps]

[event.comps."Débutants"]
  name = "Débutants"
  kind = "Jack_and_Jill"
  category = "Regular"
  leaders = 0
  follows = 0
  check_divs = true

[event.comps."Débutants".results]
  list = [{dancer = 29, role = "Follower", result = {finals = 1}}, {dancer = 30, role = "Leader", result = {finals = 1}}, {dancer = 31, role = "Follower", result = {finals = 2}}, {dancer = 32, role = "Leader", result = {finals = 2}}, {dancer = 33, role = "Follower", result = {finals = 3}}, {dancer = 34, role = "Leader", result = {finals = 3}}, {dancer = 35, role = "Leader", result = {finals = 0}}, {dancer = 36, role = "Leader", result = {finals = 0}}, {dancer = 37, role = "Follower", result = {finals = 0}}, {dancer = 38, role = "Follower", result = {finals = 0}}]

[event.comps."Confirmés"]
  name = "Confirmés"
  kind = "Jack_and_Jill"
  category = "Qualifying"
  leaders = 0
  follows = 0
  check_divs = true

[event.comps."Confirmés".results]
  list = [{dancer = 14, role = "Leader", result = {finals = 0}}, {dancer = 27, role = "Follower", result = {finals = 2}}, {dancer = 30, role = "Leader", result = {finals = 3}}, {dancer = 37, role = "Follower", result = {finals = 3}}, {dancer = 39, role = "Follower", result = {finals = 1}}, {dancer = 40, role = "Leader", result = {finals = 1}}, {dancer = 41, role = "Leader", result = {finals = 2}}, {dancer = 42, role = "Leader", result = {finals = 0}}, {dancer = 43, role = "Follower", result = {finals = 0}}, {dancer = 44, role = "Leader", result = {finals = 0}}, {dancer = 45, role = "Follower", result = {finals = 0}}, {dancer = 46, role = "Leader", result = {finals = 0}}, {dancer = 47, role = "Follower", result = {finals = 0}}, {dancer = 48, role = "Follower", result = {finals = 0}}]

[event.comps."Invités \"Old School\""]
  name = "Invités \"Old School\""
  kind = "Jack_and_Jill"
  category = "Invited"
  leaders = 0
  follows = 0
  check_divs = true

[event.comps."Invités \"Old School\"".results]
  list = [{dancer = 2, role = "Follower", result = {finals = 0}}, {dancer = 5, role = "Leader", result = {finals = 0}}, {dancer = 8, role = "Leader", result = {finals = 0}}, {dancer = 11, role = "Follower", result = {finals = 0}}, {dancer = 19, role = "Leader", result = {finals = 1}}, {dancer = 20, role = "Leader", result = {finals = 0}}, {dancer = 21, role = "Follower", result = {finals = 0}}, {dancer = 22, role = "Follower", result = {finals = 0}}, {dancer = 23, role = "Follower", result = {finals = 0}}, {dancer = 25, role = "Follower", result = {finals = 1}}, {dancer = 28, role = "Leader", result = {finals = 0}}, {dancer = 49, role = "Leader", result = {finals = 0}}, {dancer = 50, role = "Follower", result = {finals = 0}}, {dancer = 51, role = "Follower", result = {finals = 0}}, {dancer = 52, role = "Leader", result = {finals = 0}}, {dancer = 53, role = "Leader", result = {finals = 0}}]

[event.comps."Invités \"Moderne\""]
  name = "Invités \"Moderne\""
  kind = "Jack_and_Jill"
  category = "Invited"
  leaders = 0
  follows = 0
  check_divs = true

[event.comps."Invités \"Moderne\"".results]
  list = [{dancer = 2, role = "Follower", result = {finals = 0}}, {dancer = 5, role = "Leader", result = {finals = 0}}, {dancer = 8, role = "Leader", result = {finals = 0}}, {dancer = 11, role = "Follower", result = {finals = 0}}, {dancer = 19, role = "Leader", result = {finals = 0}}, {dancer = 20, role = "Leader", result = {finals = 0}}, {dancer = 21, role = "Follower", result = {finals = 0}}, {dancer = 22, role = "Follower", result = {finals = 0}}, {dancer = 23, role = "Follower", result = {finals = 0}}, {dancer = 25, role = "Follower", result = {finals = 1}}, {dancer = 28, role = "Leader", result = {finals = 0}}, {dancer = 49, role = "Leader", result = {finals = 1}}, {dancer = 50, role = "Follower", result = {finals = 0}}, {dancer = 51, role = "Follower", result = {finals = 0}}, {dancer = 52, role = "Leader", result = {finals = 0}}, {dancer = 53, role = "Leader", result = {finals = 0}}]
