/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * FTW
 * Api for the FTW dance competition scoring software
 * OpenAPI spec version: 1.0.1
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  Competition,
  CompetitionId,
  Error
} from '.././model';


type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;




/**
 * @summary Create a new competition
 */
export const putApiComp = (
    competition: Competition, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<CompetitionId>> => {
    
    
    return axios.put(
      `http://localhost:8080/api/comp`,
      competition,options
    );
  }



export const getPutApiCompMutationOptions = <TError = AxiosError<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiComp>>, TError,{data: Competition}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof putApiComp>>, TError,{data: Competition}, TContext> => {
    
const mutationKey = ['putApiComp'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putApiComp>>, {data: Competition}> = (props) => {
          const {data} = props ?? {};

          return  putApiComp(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PutApiCompMutationResult = NonNullable<Awaited<ReturnType<typeof putApiComp>>>
    export type PutApiCompMutationBody = Competition
    export type PutApiCompMutationError = AxiosError<Error>

    /**
 * @summary Create a new competition
 */
export const usePutApiComp = <TError = AxiosError<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiComp>>, TError,{data: Competition}, TContext>, axios?: AxiosRequestConfig}
): UseMutationResult<
        Awaited<ReturnType<typeof putApiComp>>,
        TError,
        {data: Competition},
        TContext
      > => {

      const mutationOptions = getPutApiCompMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * @summary Get the details of a Competition
 */
export const getApiCompId = (
    id: CompetitionId, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Competition>> => {
    
    
    return axios.get(
      `http://localhost:8080/api/comp/${id}`,options
    );
  }


export const getGetApiCompIdQueryKey = (id: CompetitionId,) => {
    return [`http://localhost:8080/api/comp/${id}`] as const;
    }

    
export const getGetApiCompIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiCompId>>, TError = AxiosError<Error>>(id: CompetitionId, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCompId>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiCompIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiCompId>>> = ({ signal }) => getApiCompId(id, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiCompId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiCompIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiCompId>>>
export type GetApiCompIdQueryError = AxiosError<Error>


export function useGetApiCompId<TData = Awaited<ReturnType<typeof getApiCompId>>, TError = AxiosError<Error>>(
 id: CompetitionId, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCompId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiCompId>>,
          TError,
          Awaited<ReturnType<typeof getApiCompId>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}

  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiCompId<TData = Awaited<ReturnType<typeof getApiCompId>>, TError = AxiosError<Error>>(
 id: CompetitionId, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCompId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiCompId>>,
          TError,
          Awaited<ReturnType<typeof getApiCompId>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiCompId<TData = Awaited<ReturnType<typeof getApiCompId>>, TError = AxiosError<Error>>(
 id: CompetitionId, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCompId>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get the details of a Competition
 */

export function useGetApiCompId<TData = Awaited<ReturnType<typeof getApiCompId>>, TError = AxiosError<Error>>(
 id: CompetitionId, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCompId>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiCompIdQueryOptions(id,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



