openapi: 3.1.0

info:
  title: Ftw
  description: |-
    Foobar

  license:
    name: GPL 3.0
    url: https://www.gnu.org/licenses/gpl-3.0.en.html
  version: 1.0.1

servers:
  - url: https://localhost:8080

tags:
  - name: event
    description: Info about events

paths:
  /events:
    get:
      tags:
        - event
      summary: get the list of events
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EventIdList'

  /event/{eventId}:
    get:
      tags:
        - event
      summary: Find event by ID
      description: Returns a single event
      parameters:
        - name: eventId
          in: path
          description: ID of event to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Event'
        '400':
          description: Invalid ID supplied
        '404':
          description: Event not found
    put:
      tags:
        - event
      summary: Create or Update an Event
      description: ''
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Event'
        required: true
      responses:
        '201':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EventId'
        '400':
          description: Invalid input

components:
  schemas:
    EventId:
      type: integer
      format: int64
      examples: [42]
    EventIdList:
      type: object
      properties:
        events:
          type: array
          items:
              $ref: '#/components/schemas/EventId'
    Event:
      type: object
      properties:
        name:
          type: string
          examples: ["P4T"]

