/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * FTW
 * Api for the FTW dance competition scoring software
 * OpenAPI spec version: 1.0.1
 */
import type { ArtefactDescriptionArtefactData } from './artefactDescriptionArtefactData';

/**
 *  artefact is either ranking or yan.
        For a ranking artefact, ranking_algorithm property should be specified.
        For a yan artefact, yan_criterion property should be set. 
 */
export interface ArtefactDescription {
  artefact?: string;
  artefact_data?: ArtefactDescriptionArtefactData;
}
