/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * FTW
 * Api for the FTW dance competition scoring software
 * OpenAPI spec version: 1.0.1
 */

export type CategoryItem = typeof CategoryItem[keyof typeof CategoryItem];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CategoryItem = {
  Novice: 'Novice',
  Intermediate: 'Intermediate',
  Advanced: 'Advanced',
  Regular: 'Regular',
  Qualifying: 'Qualifying',
  Invited: 'Invited',
} as const;
