/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * FTW
 * Api for the FTW dance competition scoring software
 * OpenAPI spec version: 1.0.1
 */
import type { EventId } from './eventId';
import type { Kind } from './kind';
import type { Category } from './category';

export interface Competition {
  event?: EventId;
  name?: string;
  kind?: Kind;
  category?: Category;
  n_leaders?: number;
  n_follows?: number;
}
