/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * FTW
 * Api for the FTW dance competition scoring software
 * OpenAPI spec version: 1.0.1
 */
import type { Date } from './date';
import type { Divisions } from './divisions';

export interface Dancer {
  birthday?: Date;
  last_name?: string;
  first_name?: string;
  email?: string;
  as_leader?: Divisions;
  as_follower?: Divisions;
}
