/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * FTW
 * Api for the FTW dance competition scoring software
 * OpenAPI spec version: 1.0.1
 */

export type DivisionItem = typeof DivisionItem[keyof typeof DivisionItem];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DivisionItem = {
  Novice: 'Novice',
  Intermediate: 'Intermediate',
  Advanced: 'Advanced',
} as const;
