/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * FTW
 * Api for the FTW dance competition scoring software
 * OpenAPI spec version: 1.0.1
 */
import type { DivisionsItem } from './divisionsItem';

export type Divisions = DivisionsItem[];
