/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * FTW
 * Api for the FTW dance competition scoring software
 * OpenAPI spec version: 1.0.1
 */

export type DivisionsItem = typeof DivisionsItem[keyof typeof DivisionsItem];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DivisionsItem = {
  None: 'None',
  Novice: 'Novice',
  Novice_Intermediate: 'Novice_Intermediate',
  Intermediate: 'Intermediate',
  Intermediate_Advanced: 'Intermediate_Advanced',
  Advanced: 'Advanced',
} as const;
