/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * FTW
 * Api for the FTW dance competition scoring software
 * OpenAPI spec version: 1.0.1
 */

export type KindItem = typeof KindItem[keyof typeof KindItem];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const KindItem = {
  Routine: 'Routine',
  Strictly: 'Strictly',
  JJ_Strictly: 'JJ_Strictly',
  Jack_and_Jill: 'Jack_and_Jill',
} as const;
