/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * FTW
 * Api for the FTW dance competition scoring software
 * OpenAPI spec version: 1.0.1
 */
import type { CompetitionId } from './competitionId';
import type { Round } from './round';
import type { ArtefactDescription } from './artefactDescription';
import type { RankingAlgorithm } from './rankingAlgorithm';

export interface Phase {
  competition?: CompetitionId;
  round?: Round;
  judge_artefact_descr?: ArtefactDescription;
  head_judge_artefact_descr?: ArtefactDescription;
  ranking_algorithm?: RankingAlgorithm;
}
