/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * FTW
 * Api for the FTW dance competition scoring software
 * OpenAPI spec version: 1.0.1
 */
import type { RankingAlgorithmAlgorithmData } from './rankingAlgorithmAlgorithmData';

/**
 *  algorithm is either ranking or yan.
        For a ranking algorithm, ranking_algorithm property should be specified.
        For a Yan_weighted algorithm, weights and head_weights properties should be set. 
 */
export interface RankingAlgorithm {
  algorithm?: string;
  algorithm_data?: RankingAlgorithmAlgorithmData;
}
