/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * FTW
 * Api for the FTW dance competition scoring software
 * OpenAPI spec version: 1.0.1
 */

export type RoundItem = typeof RoundItem[keyof typeof RoundItem];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RoundItem = {
  Prelims: 'Prelims',
  Octofinals: 'Octofinals',
  Quarterfinals: 'Quarterfinals',
  Semifinals: 'Semifinals',
  Finals: 'Finals',
} as const;
