name: Build and test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions: read-all

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout tree
        uses: actions/checkout@v6

      - name: Set-up OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: 5.0.0
          dune-cache: true

      - name: Set-up node
        uses: actions/setup-node@v6
        with:
          node-version: 23
          cache: npm
          cache-dependency-path: |
            src/frontend/package-lock.json
            src/hookgen/package-lock.json

      - name: Cache Playwright browsers
        uses: actions/cache@v5
        with:
          path: ~/.cache/ms-playwright
          key: >
            playwright-${{ runner.os }}-${{
            hashFiles('src/frontend/package-lock.json')
            }}

      - name: Install system dependencies
        # required to set OPAMASSUMEDEPEXTS: true
        run: sudo apt-get update && sudo apt-get install -y libev-dev

      - name: Configure project
        run: make configure
        env:
          OPAMASSUMEDEPEXTS: true

      - name: Build
        run: opam exec -- make

      - name: Tests
        run: opam exec -- make tests

      - name: Build the doc
        run: opam exec -- make doc