name: Build and test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions: read-all

jobs:
  build:
    runs-on: ${{ matrix.os }}

    permissions:
      contents: read

    strategy:
      fail-fast: false

      matrix:
        os:
          - ubuntu-latest
        ocaml-compiler:
          - 5.0.0

    env:
      OPAMYES: "true"

    steps:
      - name: Checkout tree
        uses: actions/checkout@v6

      - name: Set-up OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}
          dune-cache: true
          cache-prefix: v2-${{ matrix.os }}-${{ matrix.ocaml-compiler }}

      #
      # Cache the opam switch
      #
      - name: Cache opam
        uses: actions/cache@v4
        with:
          path: |
            ~/.opam
          key: >
            opam-${{ runner.os }}-${{ matrix.ocaml-compiler }}-${{
            hashFiles('**/*.opam', '**/opam.locked', '**/dune-project')
            }}
          restore-keys: |
            opam-${{ runner.os }}-${{ matrix.ocaml-compiler }}-

      - name: Set-up node
        uses: actions/setup-node@v6
        with:
          node-version: 23
          cache: npm
          cache-dependency-path: |
            src/frontend/package-lock.json
            src/hookgen/package-lock.json

      #
      # Cache Playwright browsers
      #
      - name: Cache Playwright browsers
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: >
            playwright-${{ runner.os }}-${{
            hashFiles('src/frontend/package-lock.json')
            }}

      #
      # Install dependencies once
      #
      - name: Configure project
        run: make configure

      - name: Build
        run: opam exec -- make

      - name: Tests
        run: opam exec -- make tests

      - name: Build the doc
        run: opam exec -- make doc